### ISSUE TITLE
Treafik Let's encrypt simplest example on GKE

### ISSUE THREAD

**Issue by FL3SH** [codeaprendiz/kubernetes-kitchen#1]
Hi, 
Try with two entrypoints:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`k8sacmetest.gotdns.ch`) && PathPrefix(`/tls`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls:
    certResolver: default
```
